#!/usr/bin/env ruby

$LOAD_PATH.unshift '../lib'
require 'photo_utils'
include PhotoUtils

# set up basic scene

# camera = Camera.cameras.find { |c| c.name =~ /Ikon/ }
# basic_scene = Scene.new
# basic_scene.subject_distance = 12.feet
# basic_scene.sensitivity = 3200
# basic_scene.brightness = 8
# basic_scene.description = camera.name
# basic_scene.frame = FORMATS[camera.format]

camera = Camera.cameras.find { |c| c.name =~ /RB67/ }
basic_scene = Scene.new
basic_scene.subject_distance = 8.feet
basic_scene.sensitivity = 400
basic_scene.aperture = 16
basic_scene.time = 1.0/60
# basic_scene.brightness = 32
basic_scene.description = camera.name
basic_scene.frame = FORMATS[camera.format]

scenes = []

camera.lenses.reject { |l| l.focal_length < 90 || l.focal_length == 150 }.each do |lens|
  scene = basic_scene.dup
  scene.focal_length = lens.focal_length
  # if scene.time < 1.0/15 && scene.total_depth_of_field >= 0.5.feet
    scene.description += ": #{scene.focal_length} @ #{scene.aperture}"
    scenes << scene
  # end
end

scenes.each do |scene|
  puts "#{scene.description}:"
  scene.print_depth_of_field
  scene.print_exposure
  puts
end