#!/usr/bin/env ruby

$LOAD_PATH.unshift '../lib'
require 'photo_utils'
include PhotoUtils

if Camera.cameras
  Camera.cameras.each do |camera|
    camera.print
  end
else
  warn "No cameras found."
end